CREATE DATABASE IF NOT EXISTS gaming_electronics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gaming_electronics;

CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, role ENUM('customer','admin') NOT NULL DEFAULT 'customer', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_users_email(email), KEY idx_users_role(role)) ENGINE=InnoDB;
CREATE TABLE categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT, image_url VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_categories_name(name), UNIQUE KEY uq_categories_slug(slug)) ENGINE=InnoDB;
CREATE TABLE products (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id BIGINT UNSIGNED NOT NULL, sku VARCHAR(80) NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(280) NOT NULL, short_description VARCHAR(500), description TEXT NOT NULL, brand VARCHAR(120) NOT NULL, price DECIMAL(10,2) NOT NULL, discount_price DECIMAL(10,2), stock INT UNSIGNED NOT NULL DEFAULT 0, average_rating DECIMAL(3,2) NOT NULL DEFAULT 0, review_count INT UNSIGNED NOT NULL DEFAULT 0, is_featured BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_products_category FOREIGN KEY(category_id) REFERENCES categories(id), CONSTRAINT chk_product_price CHECK(price>=0), CONSTRAINT chk_discount CHECK(discount_price IS NULL OR(discount_price>=0 AND discount_price<price)), UNIQUE KEY uq_products_sku(sku), UNIQUE KEY uq_products_slug(slug), KEY idx_products_category_active(category_id,is_active), KEY idx_products_price(price), KEY idx_products_rating(average_rating), FULLTEXT KEY ft_products_search(name,brand,short_description,description)) ENGINE=InnoDB;
CREATE TABLE product_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, image_url VARCHAR(500) NOT NULL, alt_text VARCHAR(255), sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, is_primary BOOLEAN NOT NULL DEFAULT FALSE, CONSTRAINT fk_images_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, KEY idx_images_product(product_id,sort_order)) ENGINE=InnoDB;
CREATE TABLE product_specifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, spec_key VARCHAR(120) NOT NULL, spec_value VARCHAR(255) NOT NULL, display_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, CONSTRAINT fk_specs_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, UNIQUE KEY uq_product_spec(product_id,spec_key), KEY idx_specs_search(spec_key,spec_value)) ENGINE=InnoDB;
CREATE TABLE product_customization_options (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, option_group VARCHAR(100) NOT NULL, option_name VARCHAR(150) NOT NULL, price_adjustment DECIMAL(10,2) NOT NULL DEFAULT 0, is_default BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, display_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, CONSTRAINT fk_options_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, KEY idx_options_product(product_id,option_group,is_active)) ENGINE=InnoDB;
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, order_number VARCHAR(40) NOT NULL, status ENUM('pending','paid','processing','shipped','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending', subtotal DECIMAL(10,2) NOT NULL, shipping_amount DECIMAL(10,2) NOT NULL DEFAULT 0, tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0, total_amount DECIMAL(10,2) NOT NULL, payment_status ENUM('unpaid','paid','failed','refunded') NOT NULL DEFAULT 'unpaid', stripe_payment_intent_id VARCHAR(255), shipping_name VARCHAR(160) NOT NULL, shipping_email VARCHAR(255) NOT NULL, shipping_address_line1 VARCHAR(255) NOT NULL, shipping_address_line2 VARCHAR(255), shipping_city VARCHAR(120) NOT NULL, shipping_postal_code VARCHAR(30) NOT NULL, shipping_country VARCHAR(2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_orders_user FOREIGN KEY(user_id) REFERENCES users(id), UNIQUE KEY uq_order_number(order_number), UNIQUE KEY uq_payment_intent(stripe_payment_intent_id), KEY idx_orders_user_created(user_id,created_at), KEY idx_orders_status(status,created_at)) ENGINE=InnoDB;
CREATE TABLE order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, product_name VARCHAR(255) NOT NULL, product_sku VARCHAR(80) NOT NULL, unit_price DECIMAL(10,2) NOT NULL, quantity INT UNSIGNED NOT NULL, customization_json JSON, line_total DECIMAL(10,2) NOT NULL, CONSTRAINT fk_order_items_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_order_items_product FOREIGN KEY(product_id) REFERENCES products(id), CONSTRAINT chk_quantity CHECK(quantity>0), KEY idx_items_order(order_id), KEY idx_items_product(product_id)) ENGINE=InnoDB;
CREATE TABLE reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, rating TINYINT UNSIGNED NOT NULL, title VARCHAR(180), body TEXT NOT NULL, is_approved BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_reviews_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, CONSTRAINT fk_reviews_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT chk_rating CHECK(rating BETWEEN 1 AND 5), UNIQUE KEY uq_user_product_review(user_id,product_id), KEY idx_reviews_product(product_id,is_approved,created_at)) ENGINE=InnoDB;
